/**
 * Detects CSS classes generated by a UI framework or CSS utility library, which make
 * unreliable locators (they change on library upgrades, tree-shaking and so on).
 *
 * Covers MUI v5+, Emotion, Styled-components, Tailwind, Chakra UI, Angular Material.
 * When ambiguous the class is allowed: a falsely rejected semantic class blocks locator
 * generation entirely, a missed framework class only degrades selector quality.
 *
 * Bundled into src/recorder.content.js by `npm run build`.
 */

// Single-word Tailwind layout/typography utilities that are never semantic class names
const TAILWIND_SINGLES = new Set([
  // Display
  'flex', 'grid', 'block', 'inline', 'hidden', 'contents', 'table', 'list-item',
  'inline-block', 'inline-flex', 'inline-grid', 'inline-table', 'flow-root',
  // Position
  'relative', 'absolute', 'fixed', 'sticky', 'static',
  // Visibility
  'visible', 'invisible', 'collapse',
  // Typography
  'container', 'truncate', 'antialiased', 'subpixel-antialiased',
  'italic', 'not-italic', 'underline', 'no-underline', 'line-through', 'overline',
  'uppercase', 'lowercase', 'capitalize', 'normal-case',
  // Accessibility
  'sr-only', 'not-sr-only',
  // Interactivity
  'pointer-events-none', 'pointer-events-auto',
  'resize', 'resize-none', 'resize-y', 'resize-x',
  'appearance-none', 'appearance-auto',
  'select-none', 'select-all', 'select-text', 'select-auto',
  'cursor-pointer', 'cursor-default', 'cursor-text', 'cursor-move',
  'cursor-not-allowed', 'cursor-wait', 'cursor-grab', 'cursor-grabbing',
  // Object fit
  'object-cover', 'object-contain', 'object-fill', 'object-none', 'object-scale-down',
  // Float / Clear
  'float-right', 'float-left', 'float-none',
  'clear-left', 'clear-right', 'clear-both', 'clear-none', 'clearfix',
  // Misc
  'isolate', 'isolation-auto',
  'whitespace-nowrap', 'whitespace-pre', 'whitespace-normal',
  'break-words', 'break-all', 'break-keep', 'break-normal',
  'transform', 'transform-none',
]);

/**
 * @param {string} cls - a single CSS class name
 * @returns {boolean} true if the class is framework-generated / utility-only
 */
export function isUnstableClass(cls) {
  // ── Component library prefixes ────────────────────────────────────────────
  // MUI v5+: MuiButton-root, MuiTypography-h1, MuiInputBase-input
  if (/^Mui[A-Z]/.test(cls)) return true;

  // Emotion CSS-in-JS: css-1abc123 (lowercase hex-like hash after css-)
  if (/^css-[a-z0-9]{3,}$/.test(cls)) return true;

  // Styled-components: sc-bdnxRM (sc- prefix + alphanumeric hash)
  if (/^sc-[a-zA-Z0-9]+$/.test(cls)) return true;

  // Chakra UI: chakra-button, chakra-button__icon
  if (cls.startsWith('chakra-')) return true;

  // Angular Material: mat-button, mat-icon-button, mat-form-field
  if (/^mat-[a-z]/.test(cls)) return true;

  // ── Tailwind CSS ──────────────────────────────────────────────────────────

  // Responsive / state / dark-mode variants contain colon: hover:bg-blue-500, sm:flex
  if (cls.includes(':')) return true;

  // Arbitrary value variants contain bracket: p-[20px], w-[calc(100%-2rem)]
  if (cls.includes('[')) return true;

  // Spacing: p-4, m-2, px-6, py-3, mt-auto, mx-auto, -mt-2, pb-0
  if (/^-?[mp][xytblr]?-/.test(cls)) return true;

  // Sizing: w-full, h-screen, min-w-0, max-h-96, w-1/2, size-4
  if (/^(min-|max-)?(w|h|size)-/.test(cls)) return true;

  // Gap / Space between: gap-4, gap-x-2, space-x-4, space-y-2
  if (/^(gap|space)(-[xy])?-/.test(cls)) return true;

  // Color scale utilities: bg-blue-500, text-red-400, border-gray-200, ring-indigo-300
  // Pattern: {property}-{colorName}-{shade3digits}
  if (/^(bg|text|border|ring|from|to|via|fill|stroke|shadow|decoration|accent|caret|placeholder)-[a-z]+-\d{2,3}$/.test(cls)) return true;

  // Text size tokens: text-sm, text-xl, text-2xl (not text-gray-500, handled above)
  if (/^text-(xs|sm|base|lg|xl|\d+xl)$/.test(cls)) return true;

  // Font weight / family: font-bold, font-semibold, font-sans, font-mono
  if (/^font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black|mono|sans|serif)$/.test(cls)) return true;

  // Flex utilities: flex-1, flex-row, flex-col, flex-wrap, flex-none
  // Note: flex-container, flex-header are semantic → not matched (open-ended patterns excluded)
  if (/^flex-(row|col|wrap|nowrap|none|auto|initial|\d+)(-reverse)?$/.test(cls)) return true;

  // Grid: grid-cols-3, grid-rows-4, grid-flow-col
  if (/^grid-(cols|rows|flow|span)-/.test(cls)) return true;
  // Col/Row span: col-span-2, col-start-1, row-span-3
  if (/^(col|row)-(span|start|end)-/.test(cls)) return true;

  // Order / Grow / Shrink / Basis: order-1, grow-0, shrink-0, basis-1/2
  if (/^(order|grow|shrink|basis)-/.test(cls)) return true;

  // Inset / Position values: top-0, left-4, inset-x-0, z-10, z-50
  if (/^(inset|top|right|bottom|left|z)(-[a-z0-9]+)?-\d/.test(cls)) return true;

  // Overflow: overflow-hidden, overflow-x-auto, overflow-y-scroll
  if (/^overflow(-[xy])?-/.test(cls)) return true;

  // Rounded: rounded-lg, rounded-full, rounded-t-md
  if (/^rounded(-[a-z0-9]+)*$/.test(cls) && cls !== 'rounded') return true; // bare 'rounded' below
  if (cls === 'rounded') return true;
  // Shadow: shadow-md, shadow-lg, shadow-sm, shadow-inner, shadow-none
  if (/^shadow(-[a-z0-9]+)?$/.test(cls)) return true;
  // Ring: ring-2, ring-offset-4, ring-blue-200 (color variant caught above)
  if (/^ring(-[a-z0-9]+)?$/.test(cls)) return true;
  // Outline: outline-none, outline-2, outline-dashed
  if (/^outline(-[a-z0-9]+)?$/.test(cls)) return true;
  // Border: must be specific Tailwind patterns to avoid rejecting semantic names like 'border-box'
  if (cls === 'border') return true;
  // border-{width}: border-2, border-4 (number suffix)
  if (/^border-\d+$/.test(cls)) return true;
  // border-{style}: border-solid, border-dashed, border-dotted, border-double, border-none
  if (/^border-(solid|dashed|dotted|double|hidden|none|collapse|separate)$/.test(cls)) return true;
  // border-{side}: border-t, border-b, border-l, border-r, border-x, border-y (exact, not border-box)
  if (/^border-[tblrxy](-\d+)?$/.test(cls)) return true;

  // Animation / Transform / Transition: transition-all, duration-300, ease-in, animate-spin
  if (/^(transition|duration|ease|delay|animate|scale|rotate|translate|skew|origin)(-[a-z0-9]+)?$/.test(cls)) return true;

  // Opacity: opacity-50, opacity-0
  if (/^opacity-\d+$/.test(cls)) return true;

  // Columns / Aspect / Scroll / Snap: columns-2, aspect-video, scroll-smooth
  if (/^(columns|aspect|scroll|snap|touch|will|place|self|justify|items|content)-/.test(cls)) return true;

  // Single-word utility lookup
  if (TAILWIND_SINGLES.has(cls)) return true;

  return false;
}
